# This is ".github/workflows/gh-pages.yml" file.
# This is an EXAMPLE of "GitHub Actions Workflow file".

name: kurikulum 2024 fisika

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # Publish the site
      - name: Publish
        run: dotnet publish KurikulumPascasarjanaFisika.sln -c:Release -o:publish -p:GHPages=true

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: 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
          publish_dir: publish/wwwroot
          force_orphan: true
